server:
  port: ${PORT_APP:80}

spring:
  application:
    name: atamishare

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

jwt:
  secret: b0426051adede60252f6fffd7b27ca7e1e13fa32a97c084a2da0ad13652ec426c2158c9c03393963464a2c9c465ffda60089a
  access-token-expiration: 900000 # 15分
  refresh-token-expiration: 604800000 # 7日

aws:
  ses:
    region: ${AWS_SES_REGION}
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    from-email: ${EMAIL_FROM}

app:
  cors:
    allowed-origins: http://localhost:${PORT_WEB},https://atami-share.jp
  storage:
    type: s3 # local or s3
    local-path: ${STORAGE_LOCAL_PATH}
    storage-base-url: ${STORAGE_BASE_URL}
  frontend-url: ${FRONTEND_URL}
  email:
    from: ${EMAIL_FROM}
    from-name: AtamiShare
    # s3-bucket-name: atamishare-uploads
